# Generated by Django 5.1.2 on 2025-03-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherreport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='conditions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='icon',
            field=models.CharField(default='cloudy.png', max_length=32),
        ),
        migrations.AddField(
            model_name='city',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
