# Generated by Django 5.1.2 on 2025-03-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherreport', '0002_city_conditions_city_icon_city_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='icon',
            field=models.CharField(default='none.png', max_length=32),
        ),
    ]
